### ISSUE TITLE
Split up some god-like use cases

### ISSUE THREAD

**Issue by kylecarlstrom** [CMPUT301W15T02/TeamTo#10]
Some of the use cases are "godlike." e.g. UC1.0 and UC4.0. Since they need to handle all of those User Stories, it may be easy to forget to test one specific part of them. If you break them down into smaller use cases then it is easy to have several tests each for a very specific requirement.

**Comment by rkdhatt** [comment]
I just committed a change on one of the test cases. I'm ready to split all the test cases now, I can work on splitting up UC4.0

**Comment by kylecarlstrom** [comment]
Okay sounds good!

**Comment by rkdhatt** [comment]
I added some extra use cases for UC 4, but i'm not sure if UC 4.1.1 is getting too specfic. Otherwise 4.1.2 and 4.0 seem good for now.

**Comment by kylecarlstrom** [comment]
It seems fine to me, I think that was kinda what Adam was getting at.

**Comment by rkdhatt** [comment]
Alright sounds good!
