### ISSUE TITLE
Clean up formatting in use cases

### ISSUE THREAD

**Issue by kylecarlstrom** [CMPUT301W15T02/TeamTo#2]
Mike informed me that I should put the use cases in the wiki which I have done. Unfortunately there seems to be a few formatting kinks that make it look a bit ugly. If anyone has some time and wants to clean it up a bit then go ahead. 

Specifically if there are alternate flows I can't seem to make them play nice with each other.
Also if you spot a use case that you believe is missing or needs more detail please either let me know or just add/edit it yourself.

**Comment by Stensby** [comment]
Moved the glossary from the footer to the glossary section, not sure if putting it in the footer was intentional?

**Comment by kylecarlstrom** [comment]
No for some reason it just showed up there.

**Comment by ReverseOni** [comment]
I tried adding stuff to the glossary, but I guess I added it there instead whoops haha.

**Comment by a-rankin** [comment]
I'll go over and fix the formatting now

**Comment by kylecarlstrom** [comment]
Looks good, thanks.
