### ISSUE TITLE
For claims need to check start date <= end date & for expenses need to check start date of claim <= expense date <= end date of claim

### ISSUE THREAD

**Issue by ChristineShaffer** [CMPUT301W15T02/TeamTo#22]
"Comment: So what exactly were you thinking? For example if they change the end date to before the start date do we just start adjusting the start date or do we just not make the changes?"

I was thinking that we could just toast that the end date must be >= to start date and not make the changes maybe?

**Comment by rkdhatt** [comment]
Yeah toasting it would be a lot easier



—

**Comment by Stensby** [comment]
Is there some way to set the date picker to a earliest possible date?  No idea how hard that would be, but probably the cleanest solution
