### ISSUE TITLE
When listing expenses in a claim, need to display photographic receipt

### ISSUE THREAD

**Issue by ChristineShaffer** [CMPUT301W15T02/TeamTo#23]
US 05.01.01

**Comment by a-rankin** [comment]
I found this https://github.com/siddhpuraamitr/Choose-Image-From-Gallery-Or-Camera/blob/master/src/com/example/chooseimagefromgallery/MainActivity.java 

which seems helpful.  Are we picking an image from the gallery, using the camera, or both?

**Comment by kylecarlstrom** [comment]
Likely both. If you want to use external code you need to get approval from the profs.

**Comment by rkdhatt** [comment]
Why not just use bogopic from the lab?



—

**Comment by a-rankin** [comment]
thats probably easier
