### ISSUE TITLE
Update StringTuple -> destination specifically in Create/Edit Claims

### ISSUE THREAD

**Issue by rkdhatt** [CMPUT301W15T02/TeamTo#24]
Hey guys!
Since the destinations need to have geolocation, I was thinking the destination
edit text can have a autocomplete list view pop up when a user types in a location
name. I can't imagine them typing latitude and longitude lol. This would also mean
we should have an edit text view for both destination and reason and maybe have the
list view for destinations and reasons below it. Using an alert dialog for adding destinations would
be a bit much when considering geolocation.

I found a good link for it as well:
http://android.foxykeep.com/dev/how-to-add-autocompletion-to-an-edittext

The poopy part is using FILTERS, which was such a pain with filtering tags.
Let me know your thoughts.

**Comment by kylecarlstrom** [comment]
https://developer.android.com/guide/topics/location/index.html

**Comment by rkdhatt** [comment]
Ooohh even better
