### ISSUE TITLE
Run green advisor and generate report

### ISSUE THREAD

**Issue by kylecarlstrom** [CMPUT301W15T02/TeamTo#26]
Power Use Estimation:  Try to estimate the power use of your application using the green advisor tool provided in the labs. Describe the output of the tool 1 reasonable paragraph provided on the wiki. The tool database and the the reports it generate should be committed to your git repo.

The marking criteria:
• Ran and reported tool use
• Described syscalls affected

**Comment by rkdhatt** [comment]
Just need to write the paragraph.
