### ISSUE TITLE
Inconsistent alternate use cases

### ISSUE THREAD

**Issue by a-rankin** [CMPUT301W15T02/TeamTo#3]
We are using 2 different formats for the alternate use cases. 

2a.
1. Claimant presses back before entering anything   <br>2. System does not save expense and returns to claim overview 

4a. In step 4 of the normal flow if the claimant presses back 
1. System saves the expense 
2. System returns to previous screen with new expense added 

I am not sure which one we want to use, or if one is more correct, but we should definitely make them conistent.

**Comment by kylecarlstrom** [comment]
I think 4a is probably better.
