### ISSUE TITLE
UML/Activities 

### ISSUE THREAD

**Issue by ReverseOni** [CMPUT301W15T02/TeamTo#8]
For the UML we will need to add activities to the design. Therefore, I'm thinking while we edit the UML we should also make the Activities/Layouts based off what we have. We don't have to, but it's just a thought for future efficiency.

**Comment by rkdhatt** [comment]
That sounds like a good idea! I think we should all get together in person or chat online about how we will divide the work as well, just to make sure everyone will have something to do :)
